### ISSUE TITLE
GlusterFS install

### ISSUE THREAD

**Issue by jeremycastillo** [mellanox-senior-design/docker-volume-rdma#9]
> Setting up ssd and/or ram disk

* 4 slots on servers in UTA. 1 slot in use w/ 4GB DDR3 ram stick.
* Jacob has offered to bring in personal ssd.

**Comment by JohnStarich** [comment]
Going about installation of GlusterFS via a Docker container and the appropriate `/dev` mounts.

**Comment by JohnStarich** [comment]
Backtracked a little and went for a bare-metal install of GlusterFS. Volumes can now be created, but they cannot be started.

**Comment by JohnStarich** [comment]
GlusterFS installed and @Jacobingalls got the RDMA volume started. (Apparently you have to be `force`ful)

We also installed `glusterfs-client` on donate03.
We had to change the port number on the server since it wasn't connected to by default on the client side.
